Question 1 By Borna Maherani ID = 401243079

<h1>LU decomosition function</h1>

In [5]:
import numpy as np
def LU_decmp(A, n):
    L = np.zeros((n,n))
    U = np.zeros((n,n))
    for i in range(n):
        # Upper Triangular
        for k in range(i, n):
            sum = 0
            for j in range(i):
                sum += (L[i][j] * U[j][k])
            U[i][k] = A[i][k] - sum
        # Lower Triangular
        for k in range(i, n):
            if (i == k):
                L[i][i] = 1
            else:
                sum = 0
                for j in range(i):
                    sum += (L[k][j] * U[j][i])
                L[k][i] = (A[k][i] - sum) / U[i][i]
    return L,U

A = np.array([
    [1,1,1],
    [3,1,2],
    [1,-1,1]
])
l,u=LU_decmp(A,3)
l,u

(array([[1., 0., 0.],
        [3., 1., 0.],
        [1., 1., 1.]]),
 array([[ 1.,  1.,  1.],
        [ 0., -2., -1.],
        [ 0.,  0.,  1.]]))

<h1>solving Ax=b with LU</h1>

In [6]:
def LU_solve(A,b,n):
    Y = []
    L,U = LU_decmp(A,n)
    X = []
    # LY = b
    for i in range(0, n):
        sum = 0
        for k in range (0, i):
            sum += L[i][k] * Y[k]
        temp = (b[i] - sum)/L[i][i]
        Y.insert(i,temp)
    # UX = Y 
    for i in range(n-1,-1,-1):
        sum = 0
        for k in range (n-1,i,-1):
            sum += U[i][k] * X[n-k-1]
        temp = (Y[i] - sum)/U[i][i]
        X.insert(0,temp)
    return X
b = [0,1,4]
A = np.array([
    [1,1,1],
    [3,1,2],
    [1,-1,1]
])
LU_solve(A,b,3)


[-1.0, -2.0, 3.0]

<h1>Getting input and solvind with LU methode</h1>

In [54]:
#Number of variables
n = int(input("Enter the number of variables: "))
#matrix of coefficients
A = np.empty((0,n), int)
# matrix of constants
b = []

"""
geting the coefficinets and constants(every input should be in a line and splited by 'space')
example: n=3 
1 3 4 
4
0 4 9
5
10 4 1 
6
"""
for i in range(0,n):
    line = input(f"Enter the coefficients of eq {i+1}: ").split()
    line = list(map(int, line))
    A = np.append(A, np.array([line]), axis=0)
    line = int(input(f"Enter the constants of eq {i+1}: "))
    b.append(line)

print (LU_solve(A,b,n))

[-2.6000000000000005, 1.85, -0.26666666666666666]


<h1> Test Cases </h1>

In [15]:
A = np.array([
    [1,1,1],
    [3,1,2],
    [1,-1,1]
])
b = [3,6,1]
print(LU_solve(A,b,3))

A = np.array([
    [1,1,1],
    [3,1,2],
    [1,-1,1]
])
b = [4,7,0]
print(LU_solve(A,b,3))

A = np.array([
    [1,5,0],
    [0,1,2],
    [1,0,1]
])
b = [11,0,0]
print(LU_solve(A,b,3))
LU_decmp(A,3)

[1.0, 1.0, 1.0]
[1.0, 2.0, 1.0]


(array([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 1., -5.,  1.]]),
 array([[ 1.,  5.,  0.],
        [ 0.,  1.,  2.],
        [ 0.,  0., 11.]]))